### ISSUE TITLE
SepiaFullPrediction fails with no-discrepancy model

### ISSUE THREAD

**Issue by natalieklein229** [lanl/SEPIA#17]
Error trace:

```
  File "sepia/SepiaPredict.py", line 211, in __init__
    uvPred(self)
  File "sepia/SepiaPredict.py", line 377, in uvPred
    betaV = samples['betaV'][ii, :]
KeyError: 'betaV'
```

In theory, FullPred should still work but should be able to check if no-discrepancy and handle that case.

**Comment by jgattiker** [comment]
The no-discrepancy scalar-only model is a new addition (not in GPMSA). Method not validated against gpmsa, or with real data.
