### ISSUE TITLE
Theta Constraints

### ISSUE THREAD

**Issue by jgattiker** [lanl/SEPIA#18]
A method for the user to implement (reasonably) arbitrary constraints on thetas, e.g. theta1>(theta2)**2.

**Comment by natalieklein229** [comment]
users can now pass theta_init (initial theta values following the constraint) and theta_fcon (function that evaluates the constraint on a theta array) to SepiaModel, and it will be evaluated during MCMC. A test case is in test/test_SepiaMCMC.py that confirms it does not break the code and that the sampled thetas do obey the constraint.
