### ISSUE TITLE
setup_model not working with ragged

### ISSUE THREAD

**Issue by granthutchings** [lanl/SEPIA#9]
checking that K_sim and K_obs have the same first dimension shape. Doesn't check if K_obs is a list first. ln 59.

**Comment by natalieklein229** [comment]
just pushed a probable fix - can you check if it works now, and if not, paste the code you used to check it?

**Comment by granthutchings** [comment]
this is definately the right idea for fixing the problem but it doesn't quite work with np.all because the shapes are put into a list.
in python np.all([2,2,2] == 2) is false but np.all(np.array([2,2,2]) == 2) is true so we just need the list shapes in an array not another list and it'll work!

**Comment by natalieklein229** [comment]
try it now

**Comment by granthutchings** [comment]
Working. Thanks!
